#!/bin/bash
#===============================================================================
# submit_inversion_distributed.sh
#
# Usage:
#   Test mode (2 tasks):
#     bash submit_inversion_distributed.sh --test
#
#   Full run (auto-calculated tasks based on TOTAL_ROWS and CHUNK_SIZE):
#     bash submit_inversion_distributed.sh
#
# Parameters:
#   - PROJECT_ROOT and RSCRIPT (not necessary on SMCE with default run)
#   - DATA_DIR: where are the spectral data stored (following RScript logic)
#   - OUTPUT_DIR: where outputs are written, will be created if NA
#   - CONFIG_FILE: captures User args and passes them to each SLURM Array task
#
#   - TOTAL_ROWS: total rows of data in input file (not counting header)
#   - CHUNK_SIZE: how many rows to run per SLURM TASK (assume ~1min/row + setup)
#
#   - OPTIONAL SLURM ARGS:
#      - WALLTIME: ensure it is > CHUNK_SIZE-minutes long
#      - CPUS: number of cpus per task (only relevant for parallelization in R)
#      - array: capped at 20 simultaneous tasks
#===============================================================================


# ------------------------------------------------------------------------------------
# USER INPUTS
PROJECT_ROOT="/efs/shared/users/radiative_transfer/canopyRT"
DATA_DIR="${PROJECT_ROOT}/data/compiled_data"
OUTPUT_DIR="${PROJECT_ROOT}/temp-results"
CONFIG_FILE="${OUTPUT_DIR}/job_config-testrun.sh"

# DATASET SPECIFIC INFO
TOTAL_ROWS=50
CHUNK_SIZE=25

# NOTE THESE TWO VARS ARE HARDCODED INTO THE INVERSION RScript (~lines 105-109)
# COMPILED_DATASET="NGEETropics_Leaf_Reflectance.RData"
# DATAID="Panama2016"

# SLURM OPTIONS 
MEM="8G"
WALLTIME="00:10:00"
LOG_DIR="${OUTPUT_DIR}/logs"

# OPTIONAL USER CHANGES:
JOB_SCRIPT="${PROJECT_ROOT}/pcluster/distribute_inversion_tasks.sh"
RSCRIPT="${PROJECT_ROOT}/pcluster/invert_leaf_refl_spectra_PROSPECT-pcluster.R"

# END USER INPUTS
#--------------------------------------------------------------------------------------------------#
## Derived settings — calculated from above, do not edit

N_TASKS=$(( (TOTAL_ROWS + CHUNK_SIZE - 1) / CHUNK_SIZE ))
mkdir -p "$LOG_DIR"
mkdir -p "$OUTPUT_DIR"

CPUS=1
PARTITION="demand-8cpu-c7i"

#--------------------------------------------------------------------------------------------------#
## Write config file — sourced by job script at runtime
cat > "$CONFIG_FILE" << EOF
# Auto-generated by submit_prospect_inversion.sh
# $(date)
PROJECT_ROOT="${PROJECT_ROOT}"
RSCRIPT="${RSCRIPT}"
DATA_DIR="${DATA_DIR}"
OUTPUT_DIR="${OUTPUT_DIR}"
LOG_DIR="${LOG_DIR}"
# COMPILED_DATASET="${COMPILED_DATASET}"
# DATAID="${DATAID}"
TOTAL_ROWS=${TOTAL_ROWS}
CHUNK_SIZE=${CHUNK_SIZE}
CPUS=${CPUS}
MEM="${MEM}"
EOF

echo ">>> Config written to: $CONFIG_FILE"
cat "$CONFIG_FILE"
echo ""

#--------------------------------------------------------------------------------------------------#

## Determine array range
if [ "${1}" = "--test" ]; then
  ARRAY_RANGE="1-2"
  echo "    TEST MODE: submitting 2 tasks only"
else
  ARRAY_RANGE="1-${N_TASKS}"
  echo "    FULL RUN: submitting ${N_TASKS} tasks"
  echo "    TOTAL_ROWS : $TOTAL_ROWS"
  echo "    CHUNK_SIZE : $CHUNK_SIZE"
fi

echo "    ARRAY      : $ARRAY_RANGE"
echo "    OUTPUT_DIR : $OUTPUT_DIR"
echo "    LOG_DIR    : $LOG_DIR"
echo ""

#--------------------------------------------------------------------------------------------------#

## Submit
sbatch \
  --array="${ARRAY_RANGE}%20" \
  --cpus-per-task="${CPUS}" \
  --mem="${MEM}" \
  --time="${WALLTIME}" \
  --partition="${PARTITION}" \
  --job-name="prospect_inv" \
  --output="${LOG_DIR}/prospect_%A_%a.out" \
  --error="${LOG_DIR}/prospect_%A_%a.err" \
  --export=ALL,CONFIG_FILE="$CONFIG_FILE" \
  "$JOB_SCRIPT"
#--------------------------------------------------------------------------------------------------#
